---
name: Arduino CI

on:
  push:
    paths:
      - '**/*.ino'
      - '.github/workflows/hw.yml'

jobs:
  build:
    runs-on: ubuntu-latest  # Використовуємо Ubuntu як середовище для CI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Завантажуємо код з репозиторію

    - name: Set up Arduino CLI
      uses: arduino/arduino-cli-action@v2 # Використовуємо GitHub Action для налаштування Arduino CLI
      with:
        version: 1.1.1  # Вказуємо версію Arduino CLI

    - name: Install dependencies
      run: |
        arduino-cli core update-index  # Оновлюємо список доступних ядер
        arduino-cli core install arduino:avr  # Встановлюємо ядро для Arduino UNO

    - name: Compile Arduino Sketch
      run: |
        arduino-cli compile --fqbn arduino:avr:uno ./sketch.ino  # Замість path/to/your/sketch вкажіть шлях до вашого скетчу
