---
name: Compile Arduino Code

on:
  push:
    paths:
      - '**/*.ino'
      - '.github/workflows/hw.yml'

jobs:
  compile:
    name: Compile Arduino Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: 0.32.1

      - name: Install AVR core
        run: arduino-cli core install arduino:avr

      - name: Compile Arduino Code
        run: arduino-cli compile --fqbn arduino:avr:uno
